# Generated by Django 3.2.5 on 2022-02-02 03:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_bookrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrecord',
            name='author',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bookrecord',
            name='check1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookrecord',
            name='check2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookrecord',
            name='check3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookrecord',
            name='dateEnd',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='bookrecord',
            name='dateStart',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='bookrecord',
            name='memo',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='bookrecord',
            name='publisher',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bookrecord',
            name='rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
