# Generated by Django 3.2.5 on 2022-02-18 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='books',
            new_name='bookrecords',
        ),
    ]
