# Generated by Django 3.2.5 on 2022-07-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20220729_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='imageUrl',
            field=models.URLField(default=''),
        ),
    ]
