# Generated by Django 3.2.5 on 2023-02-12 04:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20220730_2313'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookrecord',
            options={'ordering': ['-dateEnd']},
        ),
        migrations.RemoveField(
            model_name='tag',
            name='bookrecords',
        ),
        migrations.AddField(
            model_name='bookrecord',
            name='tags',
            field=models.ManyToManyField(help_text='Tags', to='books.Tag'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>', max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='bookrecord',
            name='author',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='bookrecord',
            name='publisher',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='bookrecord',
            name='rating',
            field=models.IntegerField(default=0, help_text='Stars', validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='bookrecord',
            name='title',
            field=models.CharField(max_length=256),
        ),
    ]
